default: &default
  adapter: postgresql
  username: postgres
  host: localhost
  port: 8001
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: concepts_blog_development

test:
  <<: *default
  database: concepts_blog_test

production:
  <<: *default
  database: concepts_blog
